name: R-CMD-check-DockerHub

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    name: R-CMD-check-DockerHub
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      RGL_USE_NULL: TRUE
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          install-r: false
      
      ## Create the Dockerfile based on the DESCRIPTION
      - name: Create Dockerfile
        env:
          DISPLAY: 99.0
        run: |
          install.packages(c("dockerfiler","BiocManager"))
          my_dock <- dockerfiler::dock_from_desc(repos = BiocManager::repositories())
          my_dock$write()
        shell: Rscript {0}
      
      - name: Get R package name
        run: |
          name=$(grep '^Package:' DESCRIPTION | cut -d\   -f2)
          echo "packageName=${name}" >> $GITHUB_ENV
        shell: bash {0}   
        
      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}   
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build service
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: |
            bschilder/orthogene:${{ env.packageVersion }}
            bschilder/orthogene:latest
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push service
        run: |
          docker push bschilder/orthogene:${{ env.packageVersion }}
          docker push bschilder/orthogene:latest
          